# Change these first
owner: Coltrane-Hyde # Your GitHub organization or username, where this repository lives
repo: ch-uptime # The name of this repository

sites:
  - name: ColtraneHyde
    url: https://coltranehyde.com
  - name: Leaner MVP Website
    url: https://leanermvp.com
  - name: Leaner MVP Platform
    url: https://platform.leanermvp.com
  - name: SPP Prod
    url: https://sigmapiphi.com
  - name: B2T Private
    url: https://private.theb2t.com
  - name: TBG Prod
    url: https://tbgplatform.com
  - name: B2T Website Prod
    url: https://theb2t.com
  - name: B2T Website Staging
    url: https://staging.theb2t.com/
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ch-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**ColtraneHyde Projects** - Open-source uptime monitor and status page"
  introMessage: This status page monitors the uptime and performance of **ColtraneHyde projects**, powered by GitHub Actions and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
